<a href="https://colab.research.google.com/github/sachinuttam/hackthon/blob/main/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr  = np.array([1,3,7,8])
print(arr)

[1 3 7 8]


In [5]:
import numpy as np
aa = np.array([[1,2,3],[4,5,6]])
print(aa)

[[1 2 3]
 [4 5 6]]
